/* The following code was generated by JFlex 1.6.1 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.6.1
 * from the specification file <tt>scanner2.lex</tt>
 */
class scanner2 {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;
  public static final int xtoken = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1, 1
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\1\62\1\62\1\2\22\0\1\3\1\56\1\15"+
    "\2\0\1\46\1\54\1\13\1\37\1\40\1\47\1\45\1\16\1\14"+
    "\1\10\1\50\1\7\11\6\1\60\1\57\1\53\1\51\1\52\2\0"+
    "\4\4\1\12\25\4\1\41\1\0\1\42\1\0\1\5\1\0\1\31"+
    "\1\25\1\27\1\22\1\11\1\33\1\35\1\30\1\17\2\4\1\26"+
    "\1\4\1\20\1\23\2\4\1\32\1\34\1\21\1\24\1\4\1\61"+
    "\1\36\2\4\1\43\1\55\1\44\7\0\1\62\u1fa2\0\1\62\1\62"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\2\2\1\3\2\4\1\1\1\3\1\5"+
    "\1\1\1\6\10\3\1\7\1\10\1\11\1\12\1\13"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\23"+
    "\1\24\1\25\1\26\1\27\1\30\1\3\1\31\1\32"+
    "\1\0\2\3\1\0\1\33\1\3\1\34\1\3\1\35"+
    "\13\3\2\0\1\36\1\37\1\3\1\32\1\0\2\3"+
    "\1\4\10\3\1\40\5\3\1\0\1\3\1\32\1\0"+
    "\1\41\4\3\1\42\1\43\1\44\10\3\2\0\6\3"+
    "\1\45\2\3\1\46\1\3\1\47\1\0\1\50\1\3"+
    "\1\32\1\3\1\51\1\3\1\52\1\53\1\54\1\55"+
    "\2\3\1\56\1\57";

  private static int [] zzUnpackAction() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\146\0\231\0\146\0\314\0\377\0\u0132"+
    "\0\u0165\0\u0198\0\146\0\u01cb\0\146\0\u01fe\0\u0231\0\u0264"+
    "\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363\0\146\0\146\0\146"+
    "\0\146\0\146\0\146\0\146\0\146\0\146\0\u0396\0\u03c9"+
    "\0\u03fc\0\u042f\0\146\0\146\0\146\0\146\0\146\0\u0462"+
    "\0\146\0\u0495\0\u0132\0\u04c8\0\u04fb\0\u01cb\0\146\0\u052e"+
    "\0\314\0\u0561\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\u0693"+
    "\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5\0\u07f8\0\u082b"+
    "\0\146\0\146\0\u085e\0\146\0\u0891\0\u08c4\0\u08f7\0\314"+
    "\0\u092a\0\u095d\0\u0990\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f"+
    "\0\314\0\u0ac2\0\u0af5\0\u0b28\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4"+
    "\0\u0c27\0\u0c5a\0\314\0\u0c8d\0\u0cc0\0\u0cf3\0\u0d26\0\314"+
    "\0\314\0\314\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\u0e58"+
    "\0\u0e8b\0\u0ebe\0\u0ef1\0\u0f24\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0"+
    "\0\u1023\0\u1056\0\314\0\u1089\0\u10bc\0\314\0\u10ef\0\314"+
    "\0\u0c27\0\314\0\u1122\0\314\0\u1155\0\314\0\u1188\0\314"+
    "\0\314\0\314\0\314\0\u11bb\0\u11ee\0\314\0\314";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\2\5\1\6\1\3\1\7\1\10\1\11"+
    "\1\12\1\6\1\3\1\13\1\14\1\15\1\16\2\6"+
    "\1\17\1\6\1\20\1\6\1\21\1\22\2\6\1\23"+
    "\1\24\1\25\2\6\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\1\37\1\40\1\41\1\42"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\64\51\65\0"+
    "\1\5\64\0\4\6\1\0\2\6\1\0\1\6\2\0"+
    "\20\6\22\0\1\6\7\0\2\7\1\52\60\0\2\53"+
    "\1\52\60\0\2\52\57\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\7\6\1\54\7\6\1\55\22\0\1\6"+
    "\5\0\7\56\1\0\1\56\1\57\21\56\6\0\1\56"+
    "\1\0\1\56\7\0\3\56\5\0\4\6\1\0\2\6"+
    "\1\0\1\6\2\0\1\6\1\60\12\6\1\61\3\6"+
    "\22\0\1\6\5\0\4\6\1\0\1\62\1\6\1\0"+
    "\1\6\2\0\4\6\1\63\13\6\22\0\1\6\5\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\1\6\1\64"+
    "\16\6\22\0\1\6\5\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\4\6\1\65\13\6\22\0\1\6\5\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\11\6\1\66"+
    "\1\67\5\6\22\0\1\6\5\0\4\6\1\0\1\70"+
    "\1\6\1\0\1\6\2\0\20\6\22\0\1\6\5\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\4\6\1\71"+
    "\2\6\1\72\10\6\22\0\1\6\5\0\4\6\1\0"+
    "\2\6\1\0\1\6\2\0\1\73\1\6\1\74\6\6"+
    "\1\75\6\6\22\0\1\76\50\0\1\77\1\100\64\0"+
    "\1\101\1\102\60\0\1\101\62\0\1\102\15\0\4\6"+
    "\1\0\2\6\1\0\1\6\2\0\11\6\1\103\6\6"+
    "\22\0\1\6\7\0\2\52\1\0\1\104\1\105\54\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\15\6\1\106"+
    "\2\6\22\0\1\6\5\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\107\15\6\22\0\1\6\5\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\2\6\1\110"+
    "\15\6\22\0\1\6\5\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\14\6\1\111\3\6\22\0\1\6\5\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\5\6\1\112"+
    "\12\6\22\0\1\6\5\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\15\6\1\113\2\6\22\0\1\6\5\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\1\6\1\114"+
    "\16\6\22\0\1\6\5\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\12\6\1\115\5\6\22\0\1\6\5\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\15\6\1\116"+
    "\2\6\22\0\1\6\5\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\2\6\1\117\13\6\1\120\1\6\22\0"+
    "\1\6\5\0\4\6\1\0\2\6\1\0\1\6\2\0"+
    "\13\6\1\121\4\6\22\0\1\6\5\0\4\6\1\0"+
    "\2\6\1\0\1\6\2\0\4\6\1\122\13\6\22\0"+
    "\1\6\5\0\4\6\1\0\2\6\1\0\1\6\2\0"+
    "\16\6\1\123\1\6\22\0\1\6\5\0\4\6\1\0"+
    "\2\6\1\0\1\6\2\0\12\6\1\124\5\6\22\0"+
    "\1\6\5\0\4\6\1\0\2\6\1\0\1\6\2\0"+
    "\4\6\1\125\13\6\22\0\1\6\5\0\4\6\1\0"+
    "\2\6\1\0\1\6\2\0\1\126\17\6\22\0\1\6"+
    "\1\0\47\77\1\127\13\77\1\100\1\4\1\5\57\100"+
    "\5\0\4\6\1\0\2\6\1\0\1\6\2\0\1\130"+
    "\17\6\22\0\1\6\7\0\2\131\3\0\1\132\53\0"+
    "\4\6\1\0\1\133\1\6\1\0\1\6\2\0\20\6"+
    "\22\0\1\6\5\0\4\6\1\0\1\134\1\6\1\0"+
    "\1\6\2\0\20\6\22\0\1\6\5\0\4\6\1\0"+
    "\2\6\1\0\1\6\2\0\12\6\1\135\5\6\22\0"+
    "\1\6\5\0\4\6\1\0\2\6\1\0\1\6\2\0"+
    "\6\6\1\136\11\6\22\0\1\6\5\0\4\6\1\0"+
    "\2\6\1\0\1\6\2\0\1\137\17\6\22\0\1\6"+
    "\5\0\4\6\1\0\2\6\1\0\1\6\2\0\16\6"+
    "\1\140\1\6\22\0\1\6\5\0\4\6\1\0\2\6"+
    "\1\0\1\6\2\0\13\6\1\141\4\6\22\0\1\6"+
    "\5\0\4\6\1\0\1\142\1\6\1\0\1\6\2\0"+
    "\20\6\22\0\1\6\5\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\5\6\1\143\12\6\22\0\1\6\5\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\1\144\17\6"+
    "\22\0\1\6\5\0\4\6\1\0\2\6\1\0\1\6"+
    "\2\0\12\6\1\145\5\6\22\0\1\6\5\0\4\6"+
    "\1\0\2\6\1\0\1\6\2\0\1\6\1\146\16\6"+
    "\22\0\1\6\5\0\4\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\147\15\6\22\0\1\6\5\0\4\6"+
    "\1\0\2\6\1\0\1\6\2\0\13\6\1\150\4\6"+
    "\22\0\1\6\5\0\4\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\151\15\6\22\0\1\6\1\0\47\77"+
    "\1\127\1\5\12\77\4\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\7\6\1\152\10\6\22\0\1\6\7\0"+
    "\2\131\66\0\1\153\1\154\52\0\4\6\1\0\2\6"+
    "\1\0\1\6\2\0\13\6\1\155\4\6\22\0\1\6"+
    "\5\0\4\6\1\0\2\6\1\0\1\6\2\0\5\6"+
    "\1\156\12\6\22\0\1\6\5\0\4\6\1\0\2\6"+
    "\1\0\1\6\2\0\7\6\1\157\10\6\22\0\1\6"+
    "\5\0\4\6\1\0\2\6\1\0\1\6\2\0\16\6"+
    "\1\160\1\6\22\0\1\6\5\0\4\6\1\0\2\6"+
    "\1\0\1\6\2\0\13\6\1\161\4\6\22\0\1\6"+
    "\5\0\4\6\1\0\2\6\1\0\1\6\2\0\15\6"+
    "\1\162\2\6\22\0\1\6\5\0\4\6\1\0\2\6"+
    "\1\0\1\6\2\0\2\6\1\163\15\6\22\0\1\6"+
    "\5\0\4\6\1\0\1\164\1\6\1\0\1\6\2\0"+
    "\20\6\22\0\1\6\5\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\1\165\17\6\22\0\1\6\5\0\4\6"+
    "\1\0\2\6\1\0\1\6\2\0\2\6\1\166\15\6"+
    "\22\0\1\6\5\0\4\6\1\0\2\6\1\0\1\6"+
    "\2\0\10\6\1\167\7\6\22\0\1\6\5\0\4\6"+
    "\1\0\1\170\1\6\1\0\1\6\2\0\20\6\22\0"+
    "\1\6\7\0\2\131\3\0\1\153\62\0\1\171\53\0"+
    "\4\6\1\0\2\6\1\0\1\6\2\0\1\6\1\172"+
    "\16\6\22\0\1\6\5\0\4\6\1\0\2\6\1\0"+
    "\1\6\2\0\7\6\1\173\10\6\22\0\1\6\5\0"+
    "\4\6\1\0\1\174\1\6\1\0\1\6\2\0\20\6"+
    "\22\0\1\6\5\0\4\6\1\0\2\6\1\0\1\6"+
    "\2\0\1\6\1\175\16\6\22\0\1\6\5\0\4\6"+
    "\1\0\2\6\1\0\1\6\2\0\1\6\1\176\16\6"+
    "\22\0\1\6\5\0\4\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\177\15\6\22\0\1\6\5\0\4\6"+
    "\1\0\2\6\1\0\1\6\2\0\3\6\1\200\14\6"+
    "\22\0\1\6\5\0\4\6\1\0\2\6\1\0\1\6"+
    "\2\0\10\6\1\201\7\6\22\0\1\6\5\0\4\6"+
    "\1\0\2\6\1\0\1\6\2\0\11\6\1\202\6\6"+
    "\22\0\1\6\5\0\4\6\1\0\2\6\1\0\1\6"+
    "\2\0\2\6\1\203\15\6\22\0\1\6\5\0\4\6"+
    "\1\0\1\204\1\6\1\0\1\6\2\0\20\6\22\0"+
    "\1\6\5\0\4\6\1\0\1\205\1\6\1\0\1\6"+
    "\2\0\20\6\22\0\1\6\5\0\4\6\1\0\2\6"+
    "\1\0\1\6\2\0\3\6\1\206\14\6\22\0\1\6"+
    "\5\0\4\6\1\0\2\6\1\0\1\6\2\0\13\6"+
    "\1\207\4\6\22\0\1\6\1\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4641];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\5\1\1\11\1\1\1\11"+
    "\10\1\11\11\4\1\5\11\1\1\1\11\1\1\1\0"+
    "\2\1\1\0\1\11\17\1\2\0\2\11\1\1\1\11"+
    "\1\0\21\1\1\0\2\1\1\0\20\1\2\0\14\1"+
    "\1\0\16\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[135];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private void debug(String str){
        System.out.println(str);
    }
	private Symbol symbol(int type) {
		return new Symbol(type, yyline, yycolumn);
	}
  	private Symbol symbol(int type, Object value) {
    	return new Symbol(type, yyline, yycolumn, value);
  	}



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  scanner2(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 174) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public int yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("Error, not recognized char: "+yytext());
            }
          case 48: break;
          case 2: 
            { ;
            }
          case 49: break;
          case 3: 
            { debug("TOKEN");
            }
          case 50: break;
          case 4: 
            { debug("INT");
            }
          case 51: break;
          case 5: 
            { debug("MINUS");
            }
          case 52: break;
          case 6: 
            { debug("COMMA");
            }
          case 53: break;
          case 7: 
            { debug("RO");
            }
          case 54: break;
          case 8: 
            { debug("RC");
            }
          case 55: break;
          case 9: 
            { debug("SO");
            }
          case 56: break;
          case 10: 
            { debug("SC");
            }
          case 57: break;
          case 11: 
            { debug("BO");
            }
          case 58: break;
          case 12: 
            { debug("BC");
            }
          case 59: break;
          case 13: 
            { debug("PLUS");
            }
          case 60: break;
          case 14: 
            { debug("MOD");
            }
          case 61: break;
          case 15: 
            { debug("STAR");
            }
          case 62: break;
          case 16: 
            { debug("DIV");
            }
          case 63: break;
          case 17: 
            { debug("EQ");
            }
          case 64: break;
          case 18: 
            { debug("GT");
            }
          case 65: break;
          case 19: 
            { debug("LT");
            }
          case 66: break;
          case 20: 
            { debug("AND");
            }
          case 67: break;
          case 21: 
            { debug("OR");
            }
          case 68: break;
          case 22: 
            { debug("NOT");
            }
          case 69: break;
          case 23: 
            { debug("S");
            }
          case 70: break;
          case 24: 
            { debug("C");
            }
          case 71: break;
          case 25: 
            { System.out.print(yytext());
            }
          case 72: break;
          case 26: 
            { debug("DOUBLE");
            }
          case 73: break;
          case 27: 
            { debug("STRING");
            }
          case 74: break;
          case 28: 
            { debug("IF");
            }
          case 75: break;
          case 29: 
            { debug("DO");
            }
          case 76: break;
          case 30: 
            { debug("GE");
            }
          case 77: break;
          case 31: 
            { debug("LE");
            }
          case 78: break;
          case 32: 
            { debug("FOR");
            }
          case 79: break;
          case 33: 
            { debug("ELSE");
            }
          case 80: break;
          case 34: 
            { debug("LONG");
            }
          case 81: break;
          case 35: 
            { debug("CHAR");
            }
          case 82: break;
          case 36: 
            { debug("CASE");
            }
          case 83: break;
          case 37: 
            { debug("FLOAT");
            }
          case 84: break;
          case 38: 
            { debug("SHORT");
            }
          case 85: break;
          case 39: 
            { debug("WHILE");
            }
          case 86: break;
          case 40: 
            { debug("EXTERN");
            }
          case 87: break;
          case 41: 
            { debug("RETURN");
            }
          case 88: break;
          case 42: 
            { debug("SIGNED");
            }
          case 89: break;
          case 43: 
            { debug("STATIC");
            }
          case 90: break;
          case 44: 
            { debug("SWITCH");
            }
          case 91: break;
          case 45: 
            { debug("DEFAULT");
            }
          case 92: break;
          case 46: 
            { debug("UNSIGNED");
            }
          case 93: break;
          case 47: 
            { debug("REGISTER");
            }
          case 94: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String argv[]) {
    if (argv.length == 0) {
      System.out.println("Usage : java scanner2 [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          java.nio.charset.Charset.forName(encodingName); // Side-effect: is encodingName valid? 
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        scanner2 scanner = null;
        try {
          java.io.FileInputStream stream = new java.io.FileInputStream(argv[i]);
          java.io.Reader reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new scanner2(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
      }
    }
  }


}
